### ISSUE TITLE
go-pluginserver error loop：SIGCHLD

### ISSUE THREAD

**Issue by hhofchina** [Kong/go-pluginserver#23]
2020/04/09 20:42:49 [notice] 32346#0: signal 17 (SIGCHLD) received from 19941
2020/04/09 20:42:49 [notice] 32346#0: *13 [kong] go.lua:95 go-pluginserver terminated: exit 0, context: ngx.timer
centos 7

go-pluginserver -version
Version: development
Runtime Version: go1.13.5

go-pluginserver -dump-plugin-info go-hello -plugins-directory $(pwd)
2020/04/09 20:47:47 failed to open plugin go-hello: plugin.Open("/root/go-plugins/go-hello"): plugin was built with a different version of package internal/cpu

**Comment by hhofchina** [comment]
2020/04/14 03:19:01 [notice] 20228#0: signal 17 (SIGCHLD) received from 3867
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:95 go-pluginserver terminated: exit 0, c
ontext: ngx.timer
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:84 Starting go-pluginserver, context: ng
x.timer
2020/04/14 03:19:01 [notice] 20228#0: signal 17 (SIGCHLD) received from 3873
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:95 go-pluginserver terminated: exit 0, c
ontext: ngx.timer
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:84 Starting go-pluginserver, context: ng
x.timer
2020/04/14 03:19:01 [notice] 20228#0: signal 17 (SIGCHLD) received from 3879
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:95 go-pluginserver terminated: exit 0, c
ontext: ngx.timer
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:84 Starting go-pluginserver, context: ng
x.timer
2020/04/14 03:19:01 [notice] 20228#0: signal 17 (SIGCHLD) received from 3886
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:95 go-pluginserver terminated: exit 0, c
ontext: ngx.timer
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:84 Starting go-pluginserver, context: ng
x.timer
2020/04/14 03:19:01 [notice] 20228#0: signal 17 (SIGCHLD) received from 3892
2020/04/14 03:19:01 [notice] 20228#0: *20 [kong] go.lua:95 go-pluginserver terminated: exit 0, c
ontext: ngx.timer

**Comment by hhofchina** [comment]
https://github.com/Kong/docker-kong/issues/326  may be same issue

**Comment by aquajansi2018** [comment]
兄弟解决了吗？我也遇到同样的问题，快疯掉了

**Comment by aquajansi2018** [comment]
朋友，这个SIGCHLD问题我解决了，就是修改kong.conf中的ngix配置，用一个用户来运行，不要使用nobody就可以了。但是，我现在的问题是，插件不起作用。日志已经不报错了

**Comment by gszr** [comment]
Please check out the discussion in https://github.com/Kong/docker-kong/issues/326. Make sure the Nginx process has permissions to run the pluginserver. Feel free to reopen if the issue persists for you.
