### ISSUE TITLE
go-pluginserver does not listen reload events

### ISSUE THREAD

**Issue by ealogar** [Kong/go-pluginserver#25]
Currently the pluginserver is not listening kong reload events:
- reload the balancer object in memory with all routes, services, plugins, etc...
- invalidation of the cache due to an event of route change or plugin change....

This is causing two main issues:
- Once the plugin is loaded in go-pluginserver, it can not be changed unless you kill the pluginserver itself and listen to a load event from kong
- If the initial setup of the kong plugins (global plugins) fails and stay empty, this plugin is never called again during a reload

In my use cases i use a global go plugin when configuration never changes, and i Have configured a liveness in the plugin itself to ensure it's correctly loaded

I'm afraid that all the bugs I'v seen are happening due to this

Can you take a look at it if?

**Comment by ealogar** [comment]
https://github.com/Kong/kong/issues/5586

**Comment by ealogar** [comment]
https://github.com/Kong/go-pluginserver/issues/21

**Comment by wopol** [comment]
This PR, should fix this error: https://github.com/Kong/kong/pull/5826
