### ISSUE TITLE
header_filter and body_filter event support?

### ISSUE THREAD

**Issue by zhigangfang** [Kong/go-pluginserver#28]
Hello~~~
I was developing go plugin, get request header from response. but, "kong.Response.GetHeader()" in access event method throw error below:
![Xnip2020-05-23_20-26-49](https://user-images.githubusercontent.com/3981274/82730648-d0c9cb00-9d33-11ea-8a5b-89f81b315ea9.png)

Do you support header_filter and body_filter event now？

**Comment by fffonion** [comment]
Hi @zhigangfang , please try in the new `Response` phase. Also note that `kong.Response.GetHeader(...)` returns the header in response, if you want to get request header, you will use `kong.Request.GetHeader(...)`. The later is avaiable in access phase.

**Comment by javierguerragiraldez** [comment]
Closing for lack of feedback
