### ISSUE TITLE
golang plugin can not get system environment variables in Access method

### ISSUE THREAD

**Issue by albertforweb** [Kong/go-pluginserver#34]
tried the golang plugin from here https://github.com/Kong/go-plugins/blob/master/go-hello.go

added the below into the Access method

`
var envs []string

func New() interface{} {
	envs = os.Environ()
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	kong.Log.Debug(fmt.Sprintf("global envs : %v", envs))
	kong.Log.Debug(fmt.Sprintf("environments from Access : %v", os.Environ()))
        kong.Log.Debug(fmt.Sprintf("test : %v", []string{"a", "b", "c"}))

...
`

from kong log file error.log:  
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] global envs : []
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] environments from Access : []
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] test : [a b c]

as you can see, the environment variables are empty, but there are lots of system environment variables :

% env | grep ENV
PYENV_SHELL=zsh
PYENV_VIRTUALENV_INIT=1
...

**Comment by whitesyn** [comment]
It is could be related to this: http://nginx.org/en/docs/ngx_core_module.html#env
`By default, nginx removes all environment variables inherited from its parent process except the TZ variable.`

What you can do, is to create custom nginx template file, like this one:

```
pid pids/nginx.pid;
error_log /dev/stderr debug;

env KUBERNETES_SERVICE_HOST;
env KUBERNETES_SERVICE_PORT;

# injected nginx_main_* directives
daemon off;
worker_rlimit_nofile 16384;
worker_processes auto;

events {
    # injected nginx_events_* directives
    worker_connections 16384;
    multi_accept on;
}

http {
    include 'nginx-kong.conf';
}
```

Then you'll be able to get you env variable in Go plugin: `os.Getenv("KUBERNETES_SERVICE_HOST")`

**Comment by fffonion** [comment]
Closing as it's answered above : )
