### ISSUE TITLE
Hi,Please help me to install dependences.

### ISSUE THREAD

**Issue by lampnick** [Kong/go-pluginserver#35]
Hi,The test.sh has so many dependences,can you tell me how to install the command like "rq" on macos or centos?I didn't find the command on the Internet. Thanks!
I run test.sh got the following errors:
[root@worker2 go-pluginserver]# sh test.sh 
pwd: /etc/kong/go-pluginserver
51973 go-pluginserver
Usage: rq [OPTIONS] COMMAND [ARGS]...
Try 'rq --help' for help.

Error: No such command 'at([2])'.
Ncat: No such file or directory.
Usage: rq [OPTIONS] COMMAND [ARGS]...
Try 'rq --help' for help.

Usage: rq [OPTIONS] COMMAND [ARGS]...
Try 'rq --help' for help.

Error: no such option: -M
Error: no such option: -m
query: [0, 19, "plugin.SetPluginDir", ["/etc/kong/go-pluginserver"]]
response: 
 : 
@kidd @javierguerragiraldez @kikito @ikeike443 @DMarby

**Comment by lampnick** [comment]
I had solved it . thanks

**Comment by lampnick** [comment]
@javierguerragiraldez  rq command installed. but the "hd" command not fount. I don't know what is "hd". hexdump?

**Comment by lampnick** [comment]
[root@worker2 go-pluginserver]# sh test.sh -vv
pwd: /etc/kong/go-pluginserver
113898 go-pluginserver
[
  0,
  19,
  "plugin.SetPluginDir",
  [
    "/etc/kong/go-pluginserver"
  ]
]
Usage: hd <file> [options..]
Ncat: No such file or directory.
query: [0, 19, "plugin.SetPluginDir", ["/etc/kong/go-pluginserver"]]
response: 
[0,19,"plugin.SetPluginDir",["/etc/kong/go-pluginserver"]] :

**Comment by javierguerragiraldez** [comment]
yes, `hd` is hexdump.  But don't expect too much from that script, it's not a test harness; it was used during the development of the protocol between Kong and the pluginserver.

It was continuously modified during development and slowly became unused while the "real" code matured, so I'm not actually sure it's still valid.  And of course, it doesn't exercise the whole codebase.  It should've been removed from the repo when released.

**Comment by lampnick** [comment]
> yes, `hd` is hexdump. But don't expect too much from that script, it's not a test harness; it was used during the development of the protocol between Kong and the pluginserver.
> 
> It was continuously modified during development and slowly became unused while the "real" code matured, so I'm not actually sure it's still valid. And of course, it doesn't exercise the whole codebase. It should've been removed from the repo when released.

Okay,Thank you!
