### ISSUE TITLE
fail to load go plugin on arm64

### ISSUE THREAD

**Issue by apodemakeles** [Kong/go-pluginserver#40]
I run a kong server in docker which build by myself, it works fine on amd64, but failed on arm. 
The log:
`2020/12/03 07:45:15 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/MessagePack.lua:813: missing bytes
stack traceback:
 [C]: in function 'error'
 /usr/local/share/lua/5.1/MessagePack.lua:813: in function 'underflow'
 /usr/local/share/lua/5.1/MessagePack.lua:529: in function 'unpack_cursor'
 /usr/local/share/lua/5.1/MessagePack.lua:843: in function 'unpack'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:464: in function 'get_plugin_info'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:473: in function 'get_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:515: in function 'load_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:151: in function 'load_plugin_handler'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
 /usr/local/share/lua/5.1/kong/init.lua:483: in function 'init'
 init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/MessagePack.lua:813: missing bytes
stack traceback:
 [C]: in function 'error'
 /usr/local/share/lua/5.1/MessagePack.lua:813: in function 'underflow'
 /usr/local/share/lua/5.1/MessagePack.lua:529: in function 'unpack_cursor'
 /usr/local/share/lua/5.1/MessagePack.lua:843: in function 'unpack'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:464: in function 'get_plugin_info'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:473: in function 'get_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:515: in function 'load_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:151: in function 'load_plugin_handler'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
 /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
 /usr/local/share/lua/5.1/kong/init.lua:483: in function 'init'
 init_by_lua:3: in main chunk`

No more useful informations. I have really no idea why it cannot work on arm with exactly the same Dockerfile.

the Dockerfile:
`FROM golang:1.13-alpine3.11 as builder

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk --no-cache --update add git gcc libc-dev binutils

ENV GOPROXY="http://172.26.1.9:5000"
ENV GOSUMDB="off"

RUN git clone https://github.com/Kong/go-pluginserver.git
WORKDIR ./go-pluginserver
RUN go build

RUN mkdir /go-plugins
COPY . /go-plugins/.
WORKDIR /go-plugins

RUN go mod download
RUN go build -buildmode plugin -o /go-plugins/mock.so /go-plugins/plugins/mock/mock.go
RUN go build -buildmode plugin -o /go-plugins/request_template.so /go-plugins/plugins/request_template/request_template.go

FROM kong:2.1 as artifacts

ENV KONG_GO_PLUGINSERVER_EXE="/usr/local/bin/go-pluginserver"
ENV KONG_PLUGINS="bundled,mock,request_template"
ENV KONG_GO_PLUGINS_DIR="/etc/kong/go-plugins"

USER root

COPY --from=builder /go/go-pluginserver/go-pluginserver /usr/local/bin/go-pluginserver
RUN mkdir -p /etc/kong/go-plugins
COPY --from=builder /go-plugins/mock.so /etc/kong/go-plugins/mock.so
COPY --from=builder /go-plugins/request_template.so /etc/kong/go-plugins/request_template.so

RUN chmod -R 777 /etc/kong/

USER kong`

**Comment by javierguerragiraldez** [comment]
Many things have changed since those versions.  Feel free to reopen if it's still an issue
