### ISSUE TITLE
pending eventsource with response phase

### ISSUE THREAD

**Issue by motiisr** [Kong/go-pluginserver#43]
Hi,
When in the go plugin I use the response phase hook for example:
func (conf Config) Response(kong *pdk.PDK) {
  kong.Log.Notice("This is response")
}
then in browser for the eventsource requests I get pending and finally 504.
if I remove the response and use only access it works fine.
Is there known problem with eventsource? I need the response in order to get the http code from the response.

Thanks :)

**Comment by fffonion** [comment]
Hi @motiisr , when `response` handler exists, Kong turns on response buffering and it won't work with protocol like eventsource (and possibly also websocket).

**Comment by motiisr** [comment]
@fffonion 10x for the comment. So there wont be option to get the response in eventsource in the future?

**Comment by fffonion** [comment]
@motiisr That will not be possible in the Response phase, but maybe possible with a new BodyFilter phase in the future. You should be able to inspect the response in Lua PDK for now.
