### ISSUE TITLE
plugin config changed but not take any effect in go-pluginserver

### ISSUE THREAD

**Issue by zjlletian** [Kong/go-pluginserver#44]
in demo plugin go-hello, i modify message field in konga, but still get a message which before i modified in response header.

before message config: ` lalala`
response header : `x-hello-from-go: Go says lalala to test.zjlup.com:8000`

current message config: ` emmmm`
response header : `x-hello-from-go: Go says lalala to test.zjlup.com:8000`

**Comment by fffonion** [comment]
@zjlletian could you share any debug log on Kong side after you `modify message field in konga`?

**Comment by javierguerragiraldez** [comment]
closing because of lack of feedback from author.  feel free to reopen with the debug log if the issue persists
