### ISSUE TITLE
Windows 10 + Ubuntu WSL 2.0 + go@1.13 -> cannot use ipc

### ISSUE THREAD

**Issue by JnManso** [Kong/go-pluginserver#46]
On a fresh install of Ubuntu 20.04.2.0 LTS (Focal Fossa) running on the windows 10 WSL 2. I got the error below and I'm not able to fix it.

Installation of go 1.13

 $ sudo apt remove 'golang-*'
$ wget https://dl.google.com/go/go1.13.15.linux-amd64.tar.gz
$ tar xf go1.13.15.linux-amd64.tar.gz
$ sudo mv go /usr/local/go-1.15

$ sudo nano ~/.zshrc

export GOROOT=/usr/local/go-1.13
export PATH=$GOROOT/bin:$PATH

Installation of go-pluginserver

$ go get github.com/Kong/go-pluginserver

# github.com/Kong/go-pluginserver
../go/src/github.com/Kong/go-pluginserver/event.go:49:21: cannot use ipc (type chan interface {}) as type net.Conn in argument to pdk.Init:
        chan interface {} does not implement net.Conn (missing Close method)

**Comment by fffonion** [comment]
Hi @JnManso this is a known issue where `go get` global install doesn't honor go.mod,
the short answer is to use
`GO111MODULE=on go get github.com/Kong/go-pluginserver`.
Please also see https://github.com/Kong/docker-kong/issues/458 for further reading.

**Comment by JnManso** [comment]
Thanks
