### ISSUE TITLE
Request to upgrade pdk version used

### ISSUE THREAD

**Issue by qburst-jobin** [Kong/go-pluginserver#49]
https://github.com/Kong/go-pluginserver/blob/857bc71bd9d054bab65002f76f9da2eec13addd3/go.mod#L6

Hi team,

when would the pdk version be upgraded to 0.7? 
pdk 0.7 introduced a test package which helps in testing our plugins. Currently, we are unable to use it as the plugin server used pdk 0.6 in its build.

**Comment by javierguerragiraldez** [comment]
we plan to deprecate the pluginserver itself, the recommended approach is to use the embedded server.  we've found it much easier to manage, develop and deploy.
